### ISSUE TITLE
[package request] vagrant-libvirt

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#35292]
I can't get vagrant-libvirt vagrant plugin to work with the current vagrant version.

Here the playbook I use to setup
```yaml
---
- name: install virt packages
  community.general.xbps:
    name: '{{item}}'
  loop:
      - qemu
      - libvirt
      - virt-manager
      - virt-manager-tools
      - dnsmasq
      - vagrant
      # For vagrant-libvirt
      - libvirt-devel                      
      - libguestfs
      - libxslt-devel              
      - libxml2-devel
  notify: restart libvirt

- name: add user to libvirt group
  user:
    name: '{{user}}'
    groups: libvirt
    append: yes
```

Then with my user
```bash
➜ vagrant plugin install vagrant-libvirt
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.
```

Related issue for fedora ? https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1403
